###############################################################################
#                              Configuration                                  #
###############################################################################

cuba.springContextConfig = +ru/teamscore/events/web-spring.xml

cuba.dispatcherSpringContextConfig = +ru/teamscore/events/web-dispatcher-spring.xml

cuba.persistenceConfig = +ru/teamscore/events/persistence.xml

cuba.metadataConfig = +ru/teamscore/events/metadata.xml

cuba.viewsConfig = +ru/teamscore/events/views.xml

cuba.windowConfig = +ru/teamscore/events/web-screens.xml

cuba.menuConfig = +ru/teamscore/events/web-menu.xml

cuba.permissionConfig = +ru/teamscore/events/web-permissions.xml

cuba.mainMessagePack = +ru.teamscore.events.web

cuba.anonymousSessionId = 0a711aec-3cff-fbf9-a778-1c1e2f011b17

cuba.creditsConfig = +

###############################################################################
#                                  Other                                      #
###############################################################################

# Middleware connection
cuba.connectionUrlList = http://localhost:8080/events-core

# Set to false if the middleware works on different JVM
cuba.useLocalServiceInvocation = true

cuba.webContextName = events
cuba.availableLocales = Russian|ru
cuba.localeSelectVisible = false
cuba.web.theme = hover