-- begin EVENTS_EVENT
alter table EVENTS_EVENT add constraint FK_EVENTS_EVENT_ON_RESPONSIBLE_USER foreign key (RESPONSIBLE_USER_ID) references SEC_USER(ID);
alter table EVENTS_EVENT add constraint FK_EVENTS_EVENT_ON_TYPE foreign key (TYPE_ID) references EVENTS_EVENT_TYPE(ID);
create index IDX_EVENTS_EVENT_ON_RESPONSIBLE_USER on EVENTS_EVENT (RESPONSIBLE_USER_ID);
create index IDX_EVENTS_EVENT_ON_TYPE on EVENTS_EVENT (TYPE_ID);
-- end EVENTS_EVENT

-- begin EVENTS_EVENT_TYPE
create unique index IDX_EVENTS_EVENT_TYPE_UNIQ_NAME on EVENTS_EVENT_TYPE (NAME);
-- end EVENTS_EVENT_TYPE

-- begin EVENTS_EVENT_FIELD_VALUE
alter table EVENTS_EVENT_FIELD_VALUE add constraint FK_EVENTS_EVENT_FIELD_VALUE_ON_EVENT foreign key (EVENT_ID) references EVENTS_EVENT(ID);
alter table EVENTS_EVENT_FIELD_VALUE add constraint FK_EVENTS_EVENT_FIELD_VALUE_ON_EVENT_FIELD foreign key (EVENT_FIELD_ID) references EVENTS_EVENT_FIELD(ID);
alter table EVENTS_EVENT_FIELD_VALUE add constraint FK_EVENTS_EVENT_FIELD_VALUE_ON_FILE foreign key (FILE_ID) references SYS_FILE(ID);
create index IDX_EVENTS_EVENT_FIELD_VALUE_ON_EVENT on EVENTS_EVENT_FIELD_VALUE (EVENT_ID);
create index IDX_EVENTS_EVENT_FIELD_VALUE_ON_EVENT_FIELD on EVENTS_EVENT_FIELD_VALUE (EVENT_FIELD_ID);
create index IDX_EVENTS_EVENT_FIELD_VALUE_ON_FILE on EVENTS_EVENT_FIELD_VALUE (FILE_ID);
-- end EVENTS_EVENT_FIELD_VALUE

-- begin EVENTS_EVENT_FIELD
alter table EVENTS_EVENT_FIELD add constraint FK_EVENTS_EVENT_FIELD_ON_EVENT_TYPE foreign key (EVENT_TYPE_ID) references EVENTS_EVENT_TYPE(ID);
create unique index IDX_EVENTS_EVENT_FIELD_UNIQ_ID_ on EVENTS_EVENT_FIELD (ID_);
create index IDX_EVENTS_EVENT_FIELD_ON_EVENT_TYPE on EVENTS_EVENT_FIELD (EVENT_TYPE_ID);
-- end EVENTS_EVENT_FIELD
