###############################################################################
#                              Configuration                                  #
###############################################################################

cuba.dbmsType = hsql

cuba.springContextConfig = +ru/teamscore/events/spring.xml

cuba.persistenceConfig = +ru/teamscore/events/persistence.xml

cuba.metadataConfig = +ru/teamscore/events/metadata.xml

cuba.viewsConfig = +ru/teamscore/events/views.xml

cuba.mainMessagePack = +ru.teamscore.events.core

cuba.keyForSecurityTokenEncryption = RFAzPbQozoXRr2J6

cuba.anonymousSessionId = 0a711aec-3cff-fbf9-a778-1c1e2f011b17

###############################################################################
#                                  Other                                      #
###############################################################################

cuba.webContextName = events-core
cuba.availableLocales = Russian|ru
cuba.localeSelectVisible = false

cuba.dataSourceProvider = application
cuba.dataSource.username = sa
cuba.dataSource.password =
cuba.dataSource.dbName = events-497739
cuba.dataSource.host = localhost
cuba.dataSource.port = 9010